"""workflow_improvements

Revision ID: 03644dd50cc6
Revises: 4c4802f2cc5b
Create Date: 2026-05-27 17:47:06.206922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03644dd50cc6'
down_revision: Union[str, Sequence[str], None] = '4c4802f2cc5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptom_intakes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=True),
    sa.Column('symptoms', sa.JSON(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('patients', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_patients_user_id'), 'patients', ['user_id'], unique=False)
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'])
    op.add_column('practitioners', sa.Column('specialty_category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practitioners', 'specialty_category')
    op.drop_constraint(None, 'patients', type_='foreignkey')  # type: ignore[arg-type]
    op.drop_index(op.f('ix_patients_user_id'), table_name='patients')
    op.drop_column('patients', 'user_id')
    op.drop_table('symptom_intakes')
    # ### end Alembic commands ###
