"""phase 6 clinical records

Revision ID: 245fe52ce20a
Revises: 8224a9f035a2
Create Date: 2026-05-09 20:50:49.002660

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "245fe52ce20a"
down_revision: Union[str, Sequence[str], None] = "8224a9f035a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provenance_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("target_entity_table", sa.String(), nullable=False),
        sa.Column("target_entity_id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=False),
        sa.Column("source_device_id", sa.String(), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_provenance_events_actor_user_id"),
        "provenance_events",
        ["actor_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provenance_events_target_entity_id"),
        "provenance_events",
        ["target_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provenance_events_target_entity_table"),
        "provenance_events",
        ["target_entity_table"],
        unique=False,
    )
    op.create_table(
        "allergies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("substance", sa.String(), nullable=False),
        sa.Column("criticality", sa.String(), nullable=False),
        sa.Column("record_version", sa.BigInteger(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("updated_by_user_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "criticality IN ('low', 'high', 'unable_to_assess')", name="allergies_criticality_check"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_allergies_created_by_user_id"), "allergies", ["created_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_allergies_patient_id"), "allergies", ["patient_id"], unique=False)
    op.create_table(
        "conditions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("encounter_id", sa.UUID(), nullable=True),
        sa.Column("clinical_status", sa.String(), nullable=False),
        sa.Column("disease_code", sa.String(), nullable=True),
        sa.Column("disease_name", sa.String(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "clinical_status IN ('active', 'resolved', 'inactive')", name="conditions_status_check"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conditions_created_by_user_id"), "conditions", ["created_by_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_conditions_encounter_id"), "conditions", ["encounter_id"], unique=False
    )
    op.create_index(op.f("ix_conditions_patient_id"), "conditions", ["patient_id"], unique=False)
    op.create_table(
        "medication_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("encounter_id", sa.UUID(), nullable=True),
        sa.Column("medicine_catalog_id", sa.UUID(), nullable=False),
        sa.Column("dosage_instruction", sa.String(), nullable=False),
        sa.Column("duration_days", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("record_version", sa.BigInteger(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("updated_by_user_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'completed', 'cancelled')",
            name="medication_requests_status_check",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_medication_requests_created_by_user_id"),
        "medication_requests",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_requests_encounter_id"),
        "medication_requests",
        ["encounter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_requests_medicine_catalog_id"),
        "medication_requests",
        ["medicine_catalog_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_requests_patient_id"),
        "medication_requests",
        ["patient_id"],
        unique=False,
    )
    op.create_table(
        "observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("encounter_id", sa.UUID(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("value_string", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_observations_created_by_user_id"),
        "observations",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observations_encounter_id"), "observations", ["encounter_id"], unique=False
    )
    op.create_index(
        op.f("ix_observations_patient_id"), "observations", ["patient_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_observations_patient_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_encounter_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_created_by_user_id"), table_name="observations")
    op.drop_table("observations")
    op.drop_index(op.f("ix_medication_requests_patient_id"), table_name="medication_requests")
    op.drop_index(
        op.f("ix_medication_requests_medicine_catalog_id"), table_name="medication_requests"
    )
    op.drop_index(op.f("ix_medication_requests_encounter_id"), table_name="medication_requests")
    op.drop_index(
        op.f("ix_medication_requests_created_by_user_id"), table_name="medication_requests"
    )
    op.drop_table("medication_requests")
    op.drop_index(op.f("ix_conditions_patient_id"), table_name="conditions")
    op.drop_index(op.f("ix_conditions_encounter_id"), table_name="conditions")
    op.drop_index(op.f("ix_conditions_created_by_user_id"), table_name="conditions")
    op.drop_table("conditions")
    op.drop_index(op.f("ix_allergies_patient_id"), table_name="allergies")
    op.drop_index(op.f("ix_allergies_created_by_user_id"), table_name="allergies")
    op.drop_table("allergies")
    op.drop_index(op.f("ix_provenance_events_target_entity_table"), table_name="provenance_events")
    op.drop_index(op.f("ix_provenance_events_target_entity_id"), table_name="provenance_events")
    op.drop_index(op.f("ix_provenance_events_actor_user_id"), table_name="provenance_events")
    op.drop_table("provenance_events")
    # ### end Alembic commands ###
