"""Add latitude and longitude to Prescription

Revision ID: 250a3bafeaa1
Revises: 87f52267d7ba
Create Date: 2026-05-30 08:01:52.917075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '250a3bafeaa1'
down_revision: Union[str, Sequence[str], None] = '87f52267d7ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observations_created_by_user_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_encounter_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_patient_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_table('pharmacies')
    op.drop_index(op.f('ix_prescription_items_medicine_id'), table_name='prescription_items')
    op.drop_index(op.f('ix_prescription_items_prescription_id'), table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index(op.f('ix_conditions_created_by_user_id'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_encounter_id'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_patient_id'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_stock_batches_batch_number'), table_name='stock_batches')
    op.drop_index(op.f('ix_stock_batches_medicine_id'), table_name='stock_batches')
    op.drop_index(op.f('ix_stock_batches_pharmacy_id'), table_name='stock_batches')
    op.drop_table('stock_batches')
    op.drop_index(op.f('ix_sync_conflicts_entity_id'), table_name='sync_conflicts')
    op.drop_index(op.f('ix_sync_conflicts_entity_type'), table_name='sync_conflicts')
    op.drop_table('sync_conflicts')
    op.drop_index(op.f('ix_stock_movements_batch_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_pharmacy_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_otp_challenges_phone'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_index(op.f('ix_consents_patient_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_patients_user_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('practitioners')
    op.drop_index(op.f('ix_encounter_participants_encounter_id'), table_name='encounter_participants')
    op.drop_index(op.f('ix_encounter_participants_user_id'), table_name='encounter_participants')
    op.drop_table('encounter_participants')
    op.drop_table('device_registrations')
    op.drop_index(op.f('ix_medication_requests_created_by_user_id'), table_name='medication_requests')
    op.drop_index(op.f('ix_medication_requests_encounter_id'), table_name='medication_requests')
    op.drop_index(op.f('ix_medication_requests_medicine_catalog_id'), table_name='medication_requests')
    op.drop_index(op.f('ix_medication_requests_patient_id'), table_name='medication_requests')
    op.drop_table('medication_requests')
    op.drop_index(op.f('ix_sync_cursors_cursor_token'), table_name='sync_cursors')
    op.drop_index(op.f('ix_sync_cursors_device_id'), table_name='sync_cursors')
    op.drop_index(op.f('ix_sync_cursors_user_id'), table_name='sync_cursors')
    op.drop_table('sync_cursors')
    op.drop_index(op.f('ix_consultation_notes_author_user_id'), table_name='consultation_notes')
    op.drop_index(op.f('ix_consultation_notes_encounter_id'), table_name='consultation_notes')
    op.drop_table('consultation_notes')
    op.drop_index(op.f('ix_medicine_catalog_code'), table_name='medicine_catalog')
    op.drop_index(op.f('ix_medicine_catalog_name'), table_name='medicine_catalog')
    op.drop_table('medicine_catalog')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_target_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_target_entity_type'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_document_references_appointment_id'), table_name='document_references')
    op.drop_index(op.f('ix_document_references_patient_id'), table_name='document_references')
    op.drop_index(op.f('ix_document_references_uploaded_by_user_id'), table_name='document_references')
    op.drop_table('document_references')
    op.drop_index(op.f('ix_care_loops_patient_id'), table_name='care_loops')
    op.drop_table('care_loops')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_appointments_care_loop_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_practitioner_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_scheduled_for'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('patient_identifiers')
    op.drop_index(op.f('ix_fulfillments_pharmacy_id'), table_name='fulfillments')
    op.drop_index(op.f('ix_fulfillments_prescription_id'), table_name='fulfillments')
    op.drop_table('fulfillments')
    op.drop_index(op.f('ix_provenance_events_actor_user_id'), table_name='provenance_events')
    op.drop_index(op.f('ix_provenance_events_target_entity_id'), table_name='provenance_events')
    op.drop_index(op.f('ix_provenance_events_target_entity_table'), table_name='provenance_events')
    op.drop_table('provenance_events')
    op.drop_index(op.f('ix_encounters_appointment_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_care_loop_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_practitioner_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_table('symptom_intakes')
    op.drop_index(op.f('ix_fulfillment_items_fulfillment_id'), table_name='fulfillment_items')
    op.drop_table('fulfillment_items')
    op.drop_index(op.f('ix_allergies_created_by_user_id'), table_name='allergies')
    op.drop_index(op.f('ix_allergies_patient_id'), table_name='allergies')
    op.drop_table('allergies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergies',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('substance', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('criticality', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('record_version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint("criticality::text = ANY (ARRAY['low'::character varying, 'high'::character varying, 'unable_to_assess'::character varying]::text[])", name=op.f('allergies_criticality_check')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('allergies_created_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('allergies_patient_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('allergies_updated_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('allergies_pkey'))
    )
    op.create_index(op.f('ix_allergies_patient_id'), 'allergies', ['patient_id'], unique=False)
    op.create_index(op.f('ix_allergies_created_by_user_id'), 'allergies', ['created_by_user_id'], unique=False)
    op.create_table('fulfillment_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fulfillment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('prescription_item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity_dispensed', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('quantity_dispensed > 0', name=op.f('fulfillment_items_qty_check')),
    sa.ForeignKeyConstraint(['batch_id'], ['stock_batches.id'], name=op.f('fulfillment_items_batch_id_fkey')),
    sa.ForeignKeyConstraint(['fulfillment_id'], ['fulfillments.id'], name=op.f('fulfillment_items_fulfillment_id_fkey')),
    sa.ForeignKeyConstraint(['prescription_item_id'], ['prescription_items.id'], name=op.f('fulfillment_items_prescription_item_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('fulfillment_items_pkey'))
    )
    op.create_index(op.f('ix_fulfillment_items_fulfillment_id'), 'fulfillment_items', ['fulfillment_id'], unique=False)
    op.create_table('symptom_intakes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('appointment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('raw_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('symptoms', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('symptom_intakes_appointment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('symptom_intakes_pkey'))
    )
    op.create_table('encounters',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('appointment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('practitioner_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('encounter_mode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('clinical_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('outcome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('record_version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('care_loop_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint("encounter_mode::text = ANY (ARRAY['video'::character varying, 'audio'::character varying, 'async'::character varying, 'audio_fallback'::character varying]::text[])", name=op.f('encounters_mode_check')),
    sa.CheckConstraint("status::text = ANY (ARRAY['in_progress'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])", name=op.f('encounters_status_check')),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('encounters_appointment_id_fkey')),
    sa.ForeignKeyConstraint(['care_loop_id'], ['care_loops.id'], name=op.f('encounters_care_loop_id_fkey')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('encounters_created_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('encounters_patient_id_fkey')),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], name=op.f('encounters_practitioner_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('encounters_updated_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('encounters_pkey'))
    )
    op.create_index(op.f('ix_encounters_practitioner_id'), 'encounters', ['practitioner_id'], unique=False)
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.create_index(op.f('ix_encounters_care_loop_id'), 'encounters', ['care_loop_id'], unique=False)
    op.create_index(op.f('ix_encounters_appointment_id'), 'encounters', ['appointment_id'], unique=False)
    op.create_table('provenance_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_entity_table', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('actor_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_device_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint("action::text = ANY (ARRAY['create'::character varying, 'update'::character varying, 'soft_delete'::character varying]::text[])", name=op.f('provenance_events_action_check')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('provenance_events_actor_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('provenance_events_pkey'))
    )
    op.create_index(op.f('ix_provenance_events_target_entity_table'), 'provenance_events', ['target_entity_table'], unique=False)
    op.create_index(op.f('ix_provenance_events_target_entity_id'), 'provenance_events', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_provenance_events_actor_user_id'), 'provenance_events', ['actor_user_id'], unique=False)
    op.create_table('fulfillments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('prescription_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fulfillments_created_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('fulfillments_pharmacy_id_fkey')),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('fulfillments_prescription_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('fulfillments_pkey'))
    )
    op.create_index(op.f('ix_fulfillments_prescription_id'), 'fulfillments', ['prescription_id'], unique=False)
    op.create_index(op.f('ix_fulfillments_pharmacy_id'), 'fulfillments', ['pharmacy_id'], unique=False)
    op.create_table('patient_identifiers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('identifier_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('identifier_value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('record_version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('patient_identifiers_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('patient_identifiers_pkey'))
    )
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('practitioner_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scheduled_for', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('chief_complaint', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('triage_priority', sa.VARCHAR(length=50), server_default=sa.text("'Standard'::character varying"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('care_loop_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint("channel::text = ANY (ARRAY['telemedicine'::character varying, 'assisted'::character varying]::text[])", name=op.f('appointments_channel_check')),
    sa.CheckConstraint("status::text = ANY (ARRAY['requested'::character varying, 'confirmed'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])", name=op.f('appointments_status_check')),
    sa.CheckConstraint("triage_priority::text = ANY (ARRAY['Critical'::character varying, 'Urgent'::character varying, 'Standard'::character varying]::text[])", name=op.f('appointments_triage_priority_check')),
    sa.ForeignKeyConstraint(['care_loop_id'], ['care_loops.id'], name=op.f('appointments_care_loop_id_fkey')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('appointments_created_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('appointments_patient_id_fkey')),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], name=op.f('appointments_practitioner_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('appointments_updated_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('appointments_pkey'))
    )
    op.create_index(op.f('ix_appointments_scheduled_for'), 'appointments', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_appointments_practitioner_id'), 'appointments', ['practitioner_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_care_loop_id'), 'appointments', ['care_loop_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('user_roles_role_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_roles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_roles_pkey'))
    )
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_table('care_loops',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('practitioner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('chief_complaint', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolution_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['active'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])", name=op.f('care_loops_status_check')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('care_loops_patient_id_fkey')),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], name=op.f('care_loops_practitioner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('care_loops_pkey'))
    )
    op.create_index(op.f('ix_care_loops_patient_id'), 'care_loops', ['patient_id'], unique=False)
    op.create_table('document_references',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('appointment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('document_references_appointment_id_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('document_references_patient_id_fkey')),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('document_references_uploaded_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_references_pkey'))
    )
    op.create_index(op.f('ix_document_references_uploaded_by_user_id'), 'document_references', ['uploaded_by_user_id'], unique=False)
    op.create_index(op.f('ix_document_references_patient_id'), 'document_references', ['patient_id'], unique=False)
    op.create_index(op.f('ix_document_references_appointment_id'), 'document_references', ['appointment_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('default_role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preferred_language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('refresh_token_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device_registrations.id'], name=op.f('sessions_device_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sessions_pkey'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('actor_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('audit_events_actor_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_events_pkey'))
    )
    op.create_index(op.f('ix_audit_events_target_entity_type'), 'audit_events', ['target_entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_target_entity_id'), 'audit_events', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('encounter_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('prescriptions_created_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('prescriptions_encounter_id_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('prescriptions_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('prescriptions_pkey'))
    )
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('roles_pkey'))
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('medicine_catalog',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('medicine_catalog_pkey'))
    )
    op.create_index(op.f('ix_medicine_catalog_name'), 'medicine_catalog', ['name'], unique=False)
    op.create_index(op.f('ix_medicine_catalog_code'), 'medicine_catalog', ['code'], unique=True)
    op.create_table('consultation_notes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('encounter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('author_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('note_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('record_version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('consultation_notes_author_user_id_fkey')),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('consultation_notes_encounter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('consultation_notes_pkey'))
    )
    op.create_index(op.f('ix_consultation_notes_encounter_id'), 'consultation_notes', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_consultation_notes_author_user_id'), 'consultation_notes', ['author_user_id'], unique=False)
    op.create_table('sync_cursors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('cursor_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device_registrations.id'], name=op.f('sync_cursors_device_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sync_cursors_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sync_cursors_pkey')),
    sa.UniqueConstraint('user_id', 'device_id', name=op.f('uq_sync_cursor_user_device'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_sync_cursors_user_id'), 'sync_cursors', ['user_id'], unique=False)
    op.create_index(op.f('ix_sync_cursors_device_id'), 'sync_cursors', ['device_id'], unique=False)
    op.create_index(op.f('ix_sync_cursors_cursor_token'), 'sync_cursors', ['cursor_token'], unique=False)
    op.create_table('medication_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('encounter_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('medicine_catalog_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dosage_instruction', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('duration_days', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('record_version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['active'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])", name=op.f('medication_requests_status_check')),
    sa.CheckConstraint('duration_days IS NULL OR duration_days > 0', name=op.f('medication_requests_duration_check')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('medication_requests_created_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('medication_requests_encounter_id_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('medication_requests_patient_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('medication_requests_updated_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('medication_requests_pkey'))
    )
    op.create_index(op.f('ix_medication_requests_patient_id'), 'medication_requests', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medication_requests_medicine_catalog_id'), 'medication_requests', ['medicine_catalog_id'], unique=False)
    op.create_index(op.f('ix_medication_requests_encounter_id'), 'medication_requests', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_medication_requests_created_by_user_id'), 'medication_requests', ['created_by_user_id'], unique=False)
    op.create_table('device_registrations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('device_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('app_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_trusted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('device_registrations_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('device_registrations_pkey'))
    )
    op.create_table('encounter_participants',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('encounter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('left_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('encounter_participants_encounter_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('encounter_participants_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('encounter_participants_pkey'))
    )
    op.create_index(op.f('ix_encounter_participants_user_id'), 'encounter_participants', ['user_id'], unique=False)
    op.create_index(op.f('ix_encounter_participants_encounter_id'), 'encounter_participants', ['encounter_id'], unique=False)
    op.create_table('practitioners',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('specialty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('specialty_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('registration_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('record_version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('practitioners_created_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('practitioners_updated_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('practitioners_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('practitioners_pkey'))
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preferred_language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('village', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emergency_contact_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emergency_contact_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('record_version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('patients_created_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('patients_updated_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('patients_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('patients_pkey'))
    )
    op.create_index(op.f('ix_patients_user_id'), 'patients', ['user_id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('granted_by_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['active'::character varying, 'revoked'::character varying, 'expired'::character varying]::text[])", name=op.f('consents_status_check')),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], name=op.f('consents_granted_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('consents_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('consents_pkey'))
    )
    op.create_index(op.f('ix_consents_patient_id'), 'consents', ['patient_id'], unique=False)
    op.create_table('otp_challenges',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('otp_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('otp_challenges_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('otp_challenges_pkey'))
    )
    op.create_index(op.f('ix_otp_challenges_phone'), 'otp_challenges', ['phone'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('movement_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity_change', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint("movement_type::text = ANY (ARRAY['intake'::character varying, 'adjustment'::character varying, 'dispense'::character varying]::text[])", name=op.f('stock_movements_type_check')),
    sa.CheckConstraint('quantity_change <> 0', name=op.f('stock_movements_qty_change_check')),
    sa.ForeignKeyConstraint(['batch_id'], ['stock_batches.id'], name=op.f('stock_movements_batch_id_fkey')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('stock_movements_created_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('stock_movements_pharmacy_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_movements_pkey'))
    )
    op.create_index(op.f('ix_stock_movements_pharmacy_id'), 'stock_movements', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_batch_id'), 'stock_movements', ['batch_id'], unique=False)
    op.create_table('sync_conflicts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('base_version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('server_version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('client_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('server_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('conflict_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolution_strategy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resolved_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], name=op.f('sync_conflicts_resolved_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sync_conflicts_pkey'))
    )
    op.create_index(op.f('ix_sync_conflicts_entity_type'), 'sync_conflicts', ['entity_type'], unique=False)
    op.create_index(op.f('ix_sync_conflicts_entity_id'), 'sync_conflicts', ['entity_id'], unique=False)
    op.create_table('stock_batches',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('medicine_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('batch_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('initial_quantity', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('current_quantity', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('current_quantity >= 0', name=op.f('stock_batch_current_qty_check')),
    sa.CheckConstraint('initial_quantity > 0', name=op.f('stock_batch_initial_qty_check')),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine_catalog.id'], name=op.f('stock_batches_medicine_id_fkey')),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('stock_batches_pharmacy_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_batches_pkey')),
    sa.UniqueConstraint('pharmacy_id', 'medicine_id', 'batch_number', name=op.f('uq_stock_batch'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_stock_batches_pharmacy_id'), 'stock_batches', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_stock_batches_medicine_id'), 'stock_batches', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_stock_batches_batch_number'), 'stock_batches', ['batch_number'], unique=False)
    op.create_table('conditions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('encounter_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('clinical_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('disease_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('disease_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('record_version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint("clinical_status::text = ANY (ARRAY['active'::character varying, 'resolved'::character varying, 'inactive'::character varying]::text[])", name=op.f('conditions_status_check')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('conditions_created_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('conditions_encounter_id_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('conditions_patient_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('conditions_updated_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('conditions_pkey'))
    )
    op.create_index(op.f('ix_conditions_patient_id'), 'conditions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_conditions_encounter_id'), 'conditions', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_conditions_created_by_user_id'), 'conditions', ['created_by_user_id'], unique=False)
    op.create_table('prescription_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('prescription_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('medicine_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('medicine_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dosage', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('duration_days', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('quantity_prescribed', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('quantity_prescribed > 0', name=op.f('prescription_items_qty_check')),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine_catalog.id'], name=op.f('prescription_items_medicine_id_fkey')),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('prescription_items_prescription_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('prescription_items_pkey'))
    )
    op.create_index(op.f('ix_prescription_items_prescription_id'), 'prescription_items', ['prescription_id'], unique=False)
    op.create_index(op.f('ix_prescription_items_medicine_id'), 'prescription_items', ['medicine_id'], unique=False)
    op.create_table('pharmacies',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pharmacies_pkey'))
    )
    op.create_table('observations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('encounter_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value_string', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('observations_created_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('observations_encounter_id_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('observations_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('observations_pkey'))
    )
    op.create_index(op.f('ix_observations_patient_id'), 'observations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_observations_encounter_id'), 'observations', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_observations_created_by_user_id'), 'observations', ['created_by_user_id'], unique=False)
    # ### end Alembic commands ###
