"""add_is_active_and_observation_updates

Revision ID: 3be3104a272a
Revises: b5c5f8634c40
Create Date: 2026-05-10 18:21:03.648740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be3104a272a'
down_revision: Union[str, Sequence[str], None] = 'b5c5f8634c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allergies', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('conditions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('encounters', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('medication_requests', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('observations', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('observations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'updated_at')
    op.drop_column('observations', 'is_active')
    op.drop_column('medication_requests', 'is_active')
    op.drop_column('encounters', 'is_active')
    op.drop_column('conditions', 'is_active')
    op.drop_column('allergies', 'is_active')
    # ### end Alembic commands ###
