"""add_medicine_name_to_prescription_items

Revision ID: 3f96eac560d3
Revises: 03644dd50cc6
Create Date: 2026-05-27 17:53:07.592798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f96eac560d3'
down_revision: Union[str, Sequence[str], None] = '03644dd50cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescription_items', sa.Column('medicine_name', sa.String(), nullable=True))
    op.alter_column('prescription_items', 'medicine_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prescription_items', 'medicine_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('prescription_items', 'medicine_name')
    # ### end Alembic commands ###
