"""create auth and patient tables

Revision ID: 41dd77489e0d
Revises: 0edebf5c4ca9
Create Date: 2026-05-08 10:54:48.615770

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "41dd77489e0d"
down_revision: Union[str, Sequence[str], None] = "0edebf5c4ca9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
