"""phase 5 add indexes

Revision ID: 4464f449b241
Revises: 7869b3e650c6
Create Date: 2026-05-09 20:16:28.101095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4464f449b241'
down_revision: Union[str, Sequence[str], None] = '7869b3e650c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_practitioner_id'), 'appointments', ['practitioner_id'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_for'), 'appointments', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_consultation_notes_author_user_id'), 'consultation_notes', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_consultation_notes_encounter_id'), 'consultation_notes', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_encounter_participants_encounter_id'), 'encounter_participants', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_encounter_participants_user_id'), 'encounter_participants', ['user_id'], unique=False)
    op.create_index(op.f('ix_encounters_appointment_id'), 'encounters', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.create_index(op.f('ix_encounters_practitioner_id'), 'encounters', ['practitioner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_encounters_practitioner_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_appointment_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounter_participants_user_id'), table_name='encounter_participants')
    op.drop_index(op.f('ix_encounter_participants_encounter_id'), table_name='encounter_participants')
    op.drop_index(op.f('ix_consultation_notes_encounter_id'), table_name='consultation_notes')
    op.drop_index(op.f('ix_consultation_notes_author_user_id'), table_name='consultation_notes')
    op.drop_index(op.f('ix_appointments_scheduled_for'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_practitioner_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    # ### end Alembic commands ###
