"""add_appointment_symptoms_and_triage

Revision ID: 4c4802f2cc5b
Revises: 4ecac63fb244
Create Date: 2026-05-25 21:46:15.140073

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c4802f2cc5b"
down_revision: Union[str, Sequence[str], None] = "4ecac63fb244"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "appointments", sa.Column("chief_complaint", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "appointments",
        sa.Column(
            "triage_priority", sa.String(length=50), nullable=False, server_default="Standard"
        ),
    )
    op.add_column("appointments", sa.Column("notes", sa.String(), nullable=True))
    op.create_check_constraint(
        "appointments_triage_priority_check",
        "appointments",
        "triage_priority IN ('Critical', 'Urgent', 'Standard')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("appointments_triage_priority_check", "appointments", type_="check")
    op.drop_column("appointments", "notes")
    op.drop_column("appointments", "triage_priority")
    op.drop_column("appointments", "chief_complaint")
    # ### end Alembic commands ###
