"""after phase 12

Revision ID: 4ecac63fb244
Revises: c3d8ca9d4329
Create Date: 2026-05-21 22:49:16.789324

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4ecac63fb244"
down_revision: Union[str, Sequence[str], None] = "c3d8ca9d4329"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_sync_cursor_user_device", "sync_cursors", ["user_id", "device_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_sync_cursor_user_device", "sync_cursors", type_="unique")
    # ### end Alembic commands ###
