"""Add latitude and longitude

Revision ID: 64edcf88ed01
Revises: 87f52267d7ba
Create Date: 2026-05-30 08:42:58.584837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64edcf88ed01'
down_revision: Union[str, Sequence[str], None] = '87f52267d7ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacies', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('pharmacies', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('prescriptions', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('prescriptions', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescriptions', 'longitude')
    op.drop_column('prescriptions', 'latitude')
    op.drop_column('pharmacies', 'longitude')
    op.drop_column('pharmacies', 'latitude')
    # ### end Alembic commands ###
