"""fix schema inconsistencies

Revision ID: 6f2730a6e037
Revises: 3be3104a272a
Create Date: 2026-05-12 20:40:42.974726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2730a6e037'
down_revision: Union[str, Sequence[str], None] = '3be3104a272a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allergies', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('conditions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('conditions', sa.Column('record_version', sa.BigInteger(), nullable=False))
    op.add_column('conditions', sa.Column('updated_by_user_id', sa.UUID(), nullable=True))
    op.add_column('conditions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_foreign_key(None, 'conditions', 'users', ['updated_by_user_id'], ['id'])
    op.add_column('encounters', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('medication_requests', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('observations', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('observations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'updated_at')
    op.drop_column('observations', 'is_active')
    op.drop_column('medication_requests', 'is_active')
    op.drop_column('encounters', 'is_active')
    op.drop_constraint(None, 'conditions', type_='foreignkey')
    op.drop_column('conditions', 'updated_at')
    op.drop_column('conditions', 'updated_by_user_id')
    op.drop_column('conditions', 'record_version')
    op.drop_column('conditions', 'is_active')
    op.drop_column('allergies', 'is_active')
    # ### end Alembic commands ###
