"""apply pr 6 review schema enhancements

Revision ID: 96f752318795
Revises: 098c658576d4
Create Date: 2026-05-12 21:43:28.597773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f752318795'
down_revision: Union[str, Sequence[str], None] = '098c658576d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_stock_batch', 'stock_batches', ['pharmacy_id', 'medicine_id', 'batch_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_stock_batch', 'stock_batches', type_='unique')
    # ### end Alembic commands ###
