"""phase_7_offline_sync_support

Revision ID: b5c5f8634c40
Revises: 245fe52ce20a
Create Date: 2026-05-10 18:09:43.570886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5c5f8634c40'
down_revision: Union[str, Sequence[str], None] = '245fe52ce20a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_conflicts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('base_version', sa.BigInteger(), nullable=False),
    sa.Column('server_version', sa.BigInteger(), nullable=False),
    sa.Column('client_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('server_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conflict_reason', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_strategy', sa.String(), nullable=True),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_conflicts_entity_id'), 'sync_conflicts', ['entity_id'], unique=False)
    op.create_index(op.f('ix_sync_conflicts_entity_type'), 'sync_conflicts', ['entity_type'], unique=False)
    op.create_table('sync_cursors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cursor_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device_registrations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_cursors_cursor_token'), 'sync_cursors', ['cursor_token'], unique=False)
    op.create_index(op.f('ix_sync_cursors_device_id'), 'sync_cursors', ['device_id'], unique=False)
    op.create_index(op.f('ix_sync_cursors_user_id'), 'sync_cursors', ['user_id'], unique=False)
    op.add_column('conditions', sa.Column('record_version', sa.BigInteger(), nullable=False))
    op.add_column('conditions', sa.Column('updated_by_user_id', sa.UUID(), nullable=True))
    op.add_column('conditions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_foreign_key(None, 'conditions', 'users', ['updated_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conditions', type_='foreignkey')  # type: ignore[arg-type]
    op.drop_column('conditions', 'updated_at')
    op.drop_column('conditions', 'updated_by_user_id')
    op.drop_column('conditions', 'record_version')
    op.drop_index(op.f('ix_sync_cursors_user_id'), table_name='sync_cursors')
    op.drop_index(op.f('ix_sync_cursors_device_id'), table_name='sync_cursors')
    op.drop_index(op.f('ix_sync_cursors_cursor_token'), table_name='sync_cursors')
    op.drop_table('sync_cursors')
    op.drop_index(op.f('ix_sync_conflicts_entity_type'), table_name='sync_conflicts')
    op.drop_index(op.f('ix_sync_conflicts_entity_id'), table_name='sync_conflicts')
    op.drop_table('sync_conflicts')
    # ### end Alembic commands ###
