"""apply code review schema changes

Revision ID: e86aa3437813
Revises: 6f2730a6e037
Create Date: 2026-05-12 21:06:22.559838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86aa3437813'
down_revision: Union[str, Sequence[str], None] = '6f2730a6e037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_sync_cursor_user_device', 'sync_cursors', ['user_id', 'device_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sync_cursor_user_device', 'sync_cursors', type_='unique')
    # ### end Alembic commands ###
